### ISSUE TITLE
Will characters cause out of bounds？

### ISSUE THREAD

**Issue by xiaotan277** [shivammehta25/Matcha-TTS#115]
Hello, I am a beginner in the field of speech synthesis. I used the Ljspeech dataset and the annotation text for Tacotron 2. However, the text contains characters such as "(, [,]," which prompted me during training that these characters could not be processed. I processed them using the line "_punctuation=';:,.!?" -... "" [] "()" and was able to generate normalized statistics using the YAML file configured in the dataset. However, during the subsequent training process, an error was reported, prompting me with Runtime Error: CUDA error: device side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.
Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Makefile:36: recipe for target 'train-ljspeech' failed
make: *** [train-ljspeech] Error 1。
May I ask if this issue is caused by these characters? How should I handle these characters correctly?

**Comment by shivammehta25** [comment]
It seems that the espeak version you are using is not removing brackets for some reason. If you have added additional symbols to [symbols.py](https://github.com/shivammehta25/Matcha-TTS/blob/main/matcha/text/symbols.py). You will need to increase the vocab size here increase it to the number of additional symbols you have added. It will solve your issue. 
https://github.com/shivammehta25/Matcha-TTS/blob/77804265f877b0c42f13cfdece6541dde7838090/configs/model/matcha.yaml#L9

**Comment by shivammehta25** [comment]
I have fixed this issue in the recent commits, please take a pull to fix it :)
